### PR TITLE
Update swagger.yaml

### PR DESCRIPTION
**Pull request by platfowner**
Update endpoint url on sample swagger file.

### CODE REVIEW

**Comment by pengin7384** [comment]
Can't connect https://master-ainize-run-style-transfer-ainize-team.endpoint.ainize.ai/

**Comment by platfowner** [comment]
Yes, it's because it's a pure api server. @pengin7384

**Comment by pengin7384** [comment]
Ah... I tested it again with swagger file and it works well! LGTM

**Review by pengin7384 — APPROVED** [review]

**Comment by platfowner** [comment]
@pengin7384 Thanks for the review!

**Pull request merged**
